version: "0.2"
ignorePaths: []
dictionaryDefinitions:
  - name: custom-dictionary
    path: ./.cspell/custom-dictionary.txt
    addWords: true
dictionaries:
  - custom-dictionary
words:
  - Ações
  - Básico
  - Botão
  - Camargo
  - Características
  - Conteúdo
  - criada
  - cubo
  - customizados
  - direitos
  - Enviar
  - Escuro
  - essenciais
  - Estilos
  - fixa
  - fixo
  - hambúrguer
  - Inclui
  - Inscrever
  - Karreira
  - mensagem
  - Metadados
  - moderna
  - Moderna
  - oculto
  - otimizado
  - padrão
  - portfólio
  - Portfólio
  - Preços
  - reservados
  - responsiva
  - Responsivo
  - Título
  - vindo
ignoreWords: []
import: []
